force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <label>Payment Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RandomDataCreator.cls
public with sharing class RandomDataCreator {
    public static void CreateAccounts() {
        List<Account> acc = new List<Account>();

        for (Integer i = 1; i < 6; i++) {
            Account a = new Account(
                Name = 'Test Account ' + i
            );
            acc.add(a);
        }
        insert acc;
    }

    public static void CreateOrders() {
        List<Order__c> orders = new List<Order__c>();
        List<Account> acc = [SELECT Id FROM Account WHERE Name LIKE 'Test Account%'];
        Integer numer = 1;
        
        for (Account item : acc) {
            for (Integer i = 0; i < 8; i++) {
                Order__c order = new Order__c(
                    Name = 'Test Order Numer: ' + numer,
                    Total_Amount__c = Integer.valueOf(1000 * Math.random() + 1) * 10,
                    Payment_Due_Date__c = Date.today().addDays(Integer.valueOf(Math.random() * 25)).addMonths(Integer.valueOf(Math.random() * 12)),
                    Account__c = item.Id
                );
                numer++;
                orders.add(order);
            }
        }
        insert orders;
    }
}