force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <label>Payment Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrdersResultController.cls
public with sharing class OrdersResultController {
    @AuraEnabled(Cacheable=true)
    public static List<Order__c> getOrders(String selectedAccount, String selectedMonth){
        List<Order__c> result = new List<Order__c>();
        try {
            result = fetchOrders(selectedAccount, selectedMonth);
        } catch (Exception ex){
            throw new IllegalArgumentException(Label.Error + ': ' + ex.getMessage());
        }
        return result;
    }

    private static List<Order__c> fetchOrders (String selectedAccount, String selectedMonth){
        String query = 'SELECT Id, Name, Payment_Due_Date__c, Account__c, Account__r.Name, Total_Amount__c FROM Order__c';
        if (String.isNotBlank(selectedAccount)){
            query += ' WHERE Account__c = :selectedAccount';
        }
        if (String.isNotBlank(selectedMonth) && String.isNotBlank(selectedAccount)){
            query += ' AND CALENDAR_MONTH(Payment_Due_Date__c) = ' + selectedMonth;
        }
        query += ' ORDER BY Name ASC';
        query += ' LIMIT 49999';
        return Database.query(query);
    }
}