force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <label>Payment Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/RandomDataCreatorTest.cls
@IsTest
private class RandomDataCreatorTest {
    @TestSetup
    static void setup() {
        TestDataFactory.createAccounts(5);
        TestDataFactory.createOrder(8);
    }

    @IsTest
    static void createAccountsTest() {
        RandomDataCreator.createAccounts();
        List<Account> result = [SELECT Id,
                                    Name
                                FROM Account
                                WHERE Name LIKE 'Test Account%'];
        System.assertEquals(result.size(), 10, '5 Account was created in testSetup method and 5 was be created from testing method');
    }

    @IsTest
    static void createOrdersTest() {
        RandomDataCreator.createOrders();
        List<Order__c> result = [SELECT Id,
                                    Name,
                                    Account__c,
                                    Total_Amount__c,
                                    Payment_Due_Date__c
                                FROM Order__c
                                WHERE Name LIKE 'Test Order%'];
        System.assertEquals(result.size(), 80, '40 Orders was created in testSetup and 40 was created in used testing method.');
    }
}