force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <label>Payment Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EmailHandler.cls
public without sharing class EmailHandler {
    @AuraEnabled
    public static String sendEmail(Id recordId) {
        Order__c recordToSend = [SELECT Id, Name, Total_Amount__c, Payment_Due_Date__c, Account__c FROM Order__c WHERE Id = :recordId LIMIT 1].get(0);
        Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(
            [SELECT Id, Name FROM EmailTemplate WHERE Id = '00X7Q000000y8jdUAA'].Id,
            UserInfo.getUserId(),
            recordToSend.Id);

        String subject = email.getSubject();
        String body = email.getHtmlBody();
        email.setTargetObjectId(UserInfo.getUserId());
        email.setSubject(subject);
        email.setHtmlBody(body);
        email.saveAsActivity = false;

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        return UserInfo.getUserEmail();
    }
}