force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <label>Payment Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/tests/OrdersResultControllerTest.cls
@IsTest
	private class OrdersResultControllerTest {
    @TestSetup
    static void setup() {
        TestDataFactory.createAccounts(5);
        TestDataFactory.createOrder(8);
    }

    @IsTest
    static void getOrdersWithoutArgumentsPositive() {
        List<Order__c> testResult = [SELECT Id
                                     FROM Order__c];
        System.assertEquals(testResult.size(), OrdersResultController.getOrders(null , null).size(), 'Must be 40 records from Order.');
    }

    @IsTest
    static void getOrdersWithAccountParamPositive() {
        Id acc = [SELECT Id
                  FROM Account
                  LIMIT 1].Id;
        List<Order__c> testResult = [SELECT Id,
                                        Account__c
                                     FROM Order__c
                                     WHERE Account__c = :acc];
        System.assertEquals(testResult.size(), OrdersResultController.getOrders( acc, null).size(), 'Must be 8 records from Order.');
    }

    @IsTest
    static void getOrdersPositiveTest() {
        Id acc = [SELECT Id
                  FROM Account
                  LIMIT 1].Id;
        Integer month = [SELECT Id,
                            Payment_Due_Date__c
                         FROM Order__c
                         LIMIT 1].Payment_Due_Date__c.month();

        List<Order__c> orders = [SELECT Id,
                                        Account__c,
                                        Payment_Due_Date__c
                                     FROM Order__c
                                     WHERE Account__c = :acc
                                     AND CALENDAR_MONTH(Payment_Due_Date__c) = :month];
        System.assertEquals(orders.size(), OrdersResultController.getOrders( acc, String.valueOf(month)).size(), 'Must be equals records from Order.');
    }
}