force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <label>Payment Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ordersResultController.cls
public with sharing class ordersResultController {
    @AuraEnabled(Cacheable=true)
    public static List<Order__c> getOrders(String selectedAccount, String selectedMonth) {
        List<Order__c> result = new List<Order__c>();
        if (String.isEmpty(selectedAccount) && String.isEmpty(selectedMonth)) {
            result = [SELECT Id, Name, Account__c, Payment_Due_Date__c, Total_Amount__c From Order__c LIMIT 49999];

        } else if (!String.isEmpty(selectedAccount) && String.isEmpty(selectedMonth)) {
            result = [SELECT Id, Name, Account__c, Payment_Due_Date__c, Total_Amount__c
            FROM Order__c
            WHERE Account__c IN (SELECT Id FROM Account WHERE Name LIKE :selectedAccount)
            LIMIT 49999 ];

        } else if (!String.isEmpty(selectedAccount) && !String.isEmpty(selectedMonth)) {
            for (Order__c item : [SELECT Id, Name, Account__c, Payment_Due_Date__c, Total_Amount__c
            FROM Order__c
            WHERE Account__c IN (SELECT Id FROM Account WHERE Name LIKE :selectedAccount)
            LIMIT 49999 ]) {
                String numOfMonth = String.valueOf(item.Payment_Due_Date__c.month());
                if (numOfMonth == selectedMonth) {
                    result.add(item);
                }
            }
        }
        return result;
    }
}