force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <label>Payment Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Account> createAccounts(Integer numAccts) {
        List<Account> accts = new List<Account>();
        for(Integer i = 1 ; i <= numAccts ; i++) {
            Account a = new Account(Name = 'Test Account ' + i);
            accts.add(a);
        }
        insert accts;
        return accts;
    }

    public static List<Order__c> createOrder(Integer numOrders) {
        List<Order__c> orders = new List<Order__c>();
        Integer num = 1;
        for (Account acc : [SELECT Id,
                                Name
                            FROM Account
                            WHERE Name LIKE 'Test Account %'
                            LIMIT 49999]) {
			for (Integer i = 1; i <= numOrders; i++) {
                Order__c order = new Order__c(
                    Name = 'Test Order Number: ' + num,
                    Total_Amount__c = Integer.valueOf(1000 * Math.random() + 1) * 10,
                    Payment_Due_Date__c = Date.today().addDays(Integer.valueOf(Math.random() * 25)).addMonths(Integer.valueOf(Math.random() * 12)),
                    Account__c = acc.Id
                );
                orders.add(order);
                num++;
            }
        }
        insert orders;
        return orders;
    }
}